dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    version: 0.8.8
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}